---
title: "CLR_linearmodel"
output: html_document
---

```{r}
library(phyloseq)
library(vegan)
library(dplyr)
library(tibble)
library(purrr)
library(stringr)
library(ggplot2)
library(tidyverse)
library(ggh4x)
library(lme4)
library(lmerTest)
library(broom.mixed)
```

```{r}
IBD_path <- "../data/D003093_Colitis,_Ulcerative/species/phyloseq.RData"

ps_IBD <- get(load(IBD_path))

ps_IBD_rel <- transform_sample_counts(ps_IBD, function(x) x / sum(x))
otu_IBD_rel <- as(otu_table(ps_IBD_rel), "matrix") %>% t() %>% as.data.frame()
meta_IBD_rel <- as(sample_data(ps_IBD_rel), "matrix") %>% as.data.frame()
tax_IBD_rel <- as(tax_table(ps_IBD_rel), "matrix") %>% as.data.frame()  
```

# Compositional analysis with CLR
```{r}
ps_clr <- transform_sample_counts(ps_IBD, function(x) {
  x <- x + 1e-9
  log(x) - mean(log(x))
})
otu_clr <- as(otu_table(ps_clr), "matrix") %>% t() %>% as.data.frame()
meta_clr <- as(sample_data(ps_clr), "matrix") %>% as.data.frame()
tax_clr <- as(tax_table(ps_clr), "matrix") %>% as.data.frame()

unique(meta_clr['Disease.MESH.ID'])
```

## Make long table
```{r}
dat_clr <- otu_clr %>%
  rownames_to_column("sample_id") %>%
  pivot_longer(-sample_id, names_to = "taxon", values_to = "clr") %>%
  left_join(meta_clr %>% as("data.frame") %>% rownames_to_column("sample_id"), by = "sample_id") %>%
  left_join(tax_clr %>% rownames_to_column("taxon"), by = "taxon")
```

## Test according to healthy vs sick, country
```{r}
clr_country <- subset_samples(ps_clr, Country %in% c("Denmark", "Spain", "United States of America"))
otu_clr_country <- as(otu_table(clr_country), "matrix") %>% t() %>% as.data.frame()
meta_clr_country <- as(sample_data(clr_country), "matrix") %>% as.data.frame()
tax_clr_country <- as(tax_table(clr_country), "matrix") %>% as.data.frame()

dat_clr_country <- otu_clr_country %>%
  rownames_to_column("sample_id") %>%
  pivot_longer(-sample_id, names_to = "taxon", values_to = "clr") %>%
  left_join(meta_clr %>% as("data.frame") %>% rownames_to_column("sample_id"), by = "sample_id") %>%
  left_join(tax_clr %>% rownames_to_column("taxon"), by = "taxon")

clr_status_v_country <- dat_clr_country %>%
  mutate(
    Country = factor(Country, levels = c("Denmark", "Spain", "United States of America")),
    Status = factor(Disease.MESH.ID, levels = c("D006262", "D003093"))
  ) %>%
  group_by(taxon, Genus, Species) %>%
  group_modify(~ {
    fit <- lm(
      clr ~ Country + Status,
      data = .x
    )

    broom::tidy(fit)
  }) %>%
  ungroup() %>%
  mutate(q_value = p.adjust(p.value, method = "BH"))

```

```{r}
clr_status_v_country_enriched <- clr_status_v_country %>%
  select(taxon, Genus, Species, estimate, std.error, statistic, p.value, q_value) %>%
  arrange(estimate) %>%
  head(10)

clr_status_v_country_enriched
```
```{r}
dat_clr_country %>%
  filter(taxon == clr_status_v_country_enriched %>% slice(1) %>% pull(taxon)) %>%
  ggplot(aes(x = Country, y = clr, fill = Country)) +
    geom_boxplot(outlier.shape = NA) +
    #geom_jitter(width = 0.15) +
    theme_bw()
```
